
import './App.css'
import Flashcard_list from './Flashcard_list';
 
function App() {
  
  return (
    <>
      <div className='container'>
        <Flashcard_list flashcards={  SAMPLE_FLASHCARDS }/>
      </div>
    </>
  )
}


const   SAMPLE_FLASHCARDS =[
 { id: 1,
  Question: "what is the value of pi?",
  answer: "3.14",
  options: ["3.22", "3.15", "3.66", "3,14"]},

 { id: 2,
  Question: "Array is an?",
  answer: "object",
  options: ["string", "object", "number", "undefined"]},
 { id: 3,
  Question: "js stands for?",
  answer: "JavaScript",
  options: ["HTML", "CSS", "JavaScript", "React"]},
 { id: 4,
  Question: "what is the value of 2+2?",
  answer: "4",
  options: ["1", "2", "3", "4"]},
 { id: 5,
  Question: " abbrevation of CEO?",
  answer: "Search Engine Optimization",
  options: [ "HTML", "Search Engine Optimization", "JavaScript", "React"]},
 { id: 6,
  Question: "what is the value of 2+2?",
  answer: "4",
  options: ["1", "2", "3", "4"]},
 { id: 7,
  Question: "what is the value of 2/2?",
  answer: "1",
  options: ["1", "2", "3", "4"]},
 { id: 8,
  Question: " what is your name?",
  answer: "tania",
  options: ["sonia", "sana", "asma", "tania"]},
 { id: 9,
  Question: "let is?",
  answer: "blocked-scope variable",
  options: ["global variable", "local variable", "blocked-scope variable", "4"]},
 { id: 10,
  Question: " ES6 stands for?",
  answer: "ECMAScript",
  options: [ "ECMAScript", "HTML", "CSS"]},
 { id: 11,
  Question: "what is the value of 3*2?",
  answer: "6",
  options: ["1", "2", "6", "4"]},
 { id: 12,
  Question: " push is a method of?",
  answer: "Array",
  options: ["string","Array", "object"]},
 { id: 13,
  Question: " Unary operator is?",
  answer: "both",
  options: ["increment", "decrement", "both", "none"]},
 { id: 14,
  Question: "=== is?",
  answer: "comparison operator",
  options: ["logical operator", "assignment operator", "comparison operator", "none"]},
 { id: 15,
  Question: "what is the value of pi?",
  answer: "3.14",
  options: ["3.14", "2", "3", "4"]},
 { id: 16,
  Question: " 2 is ?",
  answer: "even",
  options: ["even", "odd", "3", "4"]},
 { id: 17,
  Question: "what is the value of 2+20?",
  answer: "22",
  options: ["1", "22", "3", "4"]},
 { id: 18,
  Question: " correct answer is?",
  answer: "red",
  options: ["red", "rede", "rid", "4"]},
 { id: 19,
  Question: "pi is?",
  answer: "constant",
  options: ["variable", "contant", "both", "none"]},
 { id: 20,
  Question: " splice is a method of?",
  answer: "Array",
  options: ["Array", "string", "3", "4"]},
 { id: 21,
  Question: "what is the value of 2+2?",
  answer: "4",
  options: ["1", "2", "3", "4"]},
 { id: 22,
  Question: "what is the value of 2+2?",
  answer: "4",
  options: ["1", "2", "3", "4"]},
 { id: 23,
  Question: "what is the value of 2+2?",
  answer: "4",
  options: ["1", "2", "3", "4"]},
 { id: 24,
  Question: "what is the value of 2+2?",
  answer: "4",
  options: ["1", "2", "3", "4"]},
 { id: 25,
  Question: "what is the value of 2+2?",
  answer: "4",
  options: ["1", "2", "3", "4"]},
 { id: 26,
  Question: "what is the value of 2+2?",
  answer: "4",
  options: ["1", "2", "3", "4"]},
 { id: 27,
  Question: "what is the value of 2+2?",
  answer: "4",
  options: ["1", "2", "3", "4"]},
 { id: 28,
  Question: "what is the value of 2+2?",
  answer: "4",
  options: ["1", "2", "3", "4"]},
 { id: 29,
  Question: "what is the value of 2+2?",
  answer: "4",
  options: ["1", "2", "3", "4"]},
 { id: 30,
  Question: "sum of 5+18?",
  answer: "23",
  options: ["1", "23", "3", "4"]}
  
]

export default App
